-- MySQL Script generated by MySQL Workbench
-- 12/09/16 09:54:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema schoolcheck
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema schoolcheck
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schoolcheck` DEFAULT CHARACTER SET utf8 ;
USE `schoolcheck` ;

-- -----------------------------------------------------
-- Table `schoolcheck`.`Schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `streetname` VARCHAR(45) NULL,
  `streetnumber` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `telnr` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  `opdenday` VARCHAR(45) NULL,
  `infonight` VARCHAR(45) NULL,
  `openclass` VARCHAR(45) NULL,
  `concept` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Districts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Concept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Concept` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Specials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Specials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Schools_has_Levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Schools_has_Levels` (
  `Schools_id` INT NOT NULL,
  `Levels_id` INT NOT NULL,
  PRIMARY KEY (`Schools_id`, `Levels_id`),
  INDEX `fk_Schools_has_Levels_Levels1_idx` (`Levels_id` ASC),
  INDEX `fk_Schools_has_Levels_Schools1_idx` (`Schools_id` ASC),
  CONSTRAINT `fk_Schools_has_Levels_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `schoolcheck`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schools_has_Levels_Levels1`
    FOREIGN KEY (`Levels_id`)
    REFERENCES `schoolcheck`.`Levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Schools_has_Specials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Schools_has_Specials` (
  `Schools_id` INT NOT NULL,
  `Specials_id` INT NOT NULL,
  PRIMARY KEY (`Schools_id`, `Specials_id`),
  INDEX `fk_Schools_has_Specials_Specials1_idx` (`Specials_id` ASC),
  INDEX `fk_Schools_has_Specials_Schools1_idx` (`Schools_id` ASC),
  CONSTRAINT `fk_Schools_has_Specials_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `schoolcheck`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schools_has_Specials_Specials1`
    FOREIGN KEY (`Specials_id`)
    REFERENCES `schoolcheck`.`Specials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `schoolcheck`.`Schools_has_openclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `schoolcheck`.`Schools_has_openclass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Schools_has_openclasscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
