-- MySQL Script generated by MySQL Workbench
-- 11/30/16 11:03:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Districts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Districts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consept` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schools`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `streetname` VARCHAR(45) NULL,
  `streetnumber` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `district` VARCHAR(45) NULL,
  `telnr` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  `openday` DATETIME NULL,
  `openday 2` DATETIME NULL,
  `openday 3` DATETIME NULL,
  `openclass` DATETIME NULL,
  `openclass 2` DATETIME NULL,
  `infonight` DATETIME NULL,
  `prive` TINYINT(1) NULL,
  `districts_id` INT NOT NULL,
  `Consept_id` INT NOT NULL,
  PRIMARY KEY (`id`, `districts_id`, `Consept_id`),
  INDEX `fk_school_districts_idx` (`districts_id` ASC),
  INDEX `fk_Schools_Consept1_idx` (`Consept_id` ASC),
  CONSTRAINT `fk_school_districts`
    FOREIGN KEY (`districts_id`)
    REFERENCES `mydb`.`Districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schools_Consept1`
    FOREIGN KEY (`Consept_id`)
    REFERENCES `mydb`.`Consept` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Levels` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schools-levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schools-levels` (
  `Schools_id` INT NOT NULL,
  `Levels_id` INT NOT NULL,
  PRIMARY KEY (`Schools_id`, `Levels_id`),
  INDEX `fk_Schools-levels_Schools1_idx` (`Schools_id` ASC),
  INDEX `fk_Schools-levels_Levels1_idx` (`Levels_id` ASC),
  CONSTRAINT `fk_Schools-levels_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `mydb`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schools-levels_Levels1`
    FOREIGN KEY (`Levels_id`)
    REFERENCES `mydb`.`Levels` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Specials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schools-specials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schools-specials` (
  `Specials_id` INT NOT NULL,
  `Schools_id` INT NOT NULL,
  PRIMARY KEY (`Specials_id`, `Schools_id`),
  INDEX `fk_Schools-specials_Specials1_idx` (`Specials_id` ASC),
  INDEX `fk_Schools-specials_Schools1_idx` (`Schools_id` ASC),
  CONSTRAINT `fk_Schools-specials_Specials1`
    FOREIGN KEY (`Specials_id`)
    REFERENCES `mydb`.`Specials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Schools-specials_Schools1`
    FOREIGN KEY (`Schools_id`)
    REFERENCES `mydb`.`Schools` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
